import hashlib
import os
from pathlib import Path

LANG_BY_EXT = {
    ".py": "python",
    ".js": "javascript", ".jsx": "javascript",
    ".mjs": "javascript", ".cjs": "javascript",
    ".ts": "typescript", ".tsx": "typescript",
    ".go": "go",
    ".rs": "rust",
    ".c": "c", ".h": "c",
    ".cc": "cpp", ".cpp": "cpp", ".cxx": "cpp",
    ".hpp": "cpp", ".hh": "cpp", ".hxx": "cpp",
    ".java": "java",
    ".rb": "ruby",
    ".cs": "csharp",
    ".kt": "kotlin", ".kts": "kotlin",
    ".swift": "swift",
    ".php": "php",
    ".scala": "scala",
    ".sh": "bash", ".bash": "bash",
    ".json": "json",
    ".yml": "yaml", ".yaml": "yaml",
    ".toml": "toml",
}

# File extensions that are PURE documentation / prose. The contract
# extractor's regex patterns (`--flag`, `process.env.X`) match
# documentation chatter and create false-positive contracts when run on
# these. We MUST skip them. See audit P0 (`projmem complete` flagged
# every flag mention in AGENTS.md as an "open obligation").
DOC_ONLY_EXTENSIONS = {
    ".md", ".markdown", ".txt", ".rst", ".adoc", ".asciidoc", ".org",
    ".rtf",
}


def is_doc_only(path: str) -> bool:
    """True iff the path's extension is documentation-only (no
    contract extraction)."""
    if not path:
        return False
    ext = os.path.splitext(path)[1].lower()
    return ext in DOC_ONLY_EXTENSIONS


SKIP_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "__pycache__", ".venv", "venv",
    "env", "dist", "build", ".next", ".cache", ".tox", ".mypy_cache",
    ".pytest_cache", ".projmem", ".idea", ".vscode", "target", "out",
    "coverage", ".nyc_output",
    # Self-test found: Python packaging artifacts were being indexed.
    # `*.egg-info/` is generated by setuptools and always contains
    # derivative files (PKG-INFO, SOURCES.txt, entry_points.txt, etc.).
    # axios eval surfaced: projmem's own output directory was getting
    # indexed, so subsequent contract-diff/symbol-diff runs flagged
    # synthetic schema_field contracts on graph.mmd / REPORT.md as
    # "added contracts". Skip projmem-out/ by default.
    "projmem-out",
}

# Directory suffixes to prune. Complements SKIP_DIRS where the directory
# NAME varies (e.g. `projmem.egg-info`, `pkg.egg-info`) but the suffix is
# canonical.
SKIP_DIR_SUFFIXES = (
    ".egg-info",
    ".dist-info",
)


# Map a shebang interpreter name (last path segment) → our internal lang
# label. Used when a file has no recognizable extension; prevents a
# Perl build script or a POSIX shell script from being parsed as C by
# the regex fallback.
_SHEBANG_LANG = {
    "python": "python", "python2": "python", "python3": "python",
    "node": "javascript", "nodejs": "javascript",
    "bash": "bash", "sh": "bash", "dash": "bash", "zsh": "bash",
    "ksh": "bash", "ash": "bash",
    "perl": "perl",
    "ruby": "ruby",
    "php": "php",
    "lua": "lua",
}

# Map a vim/emacs modeline language token → our internal lang label.
_MODELINE_LANG = {
    "python": "python", "perl": "perl", "ruby": "ruby", "bash": "bash",
    "sh": "bash", "c": "c", "c++": "cpp", "cpp": "cpp", "cxx": "cpp",
    "javascript": "javascript", "js": "javascript",
    "typescript": "typescript", "ts": "typescript",
    "go": "go", "rust": "rust",
}


def _sniff_first_line(path: str) -> str:
    """Read just the first line of `path` for shebang/modeline inspection.
    Bounded at 256 bytes — malformed binaries won't drag us into a full
    read."""
    try:
        with open(path, "rb") as f:
            chunk = f.read(256)
    except (OSError, PermissionError):
        return ""
    try:
        return chunk.decode("utf-8", errors="replace").splitlines()[0]
    except IndexError:
        return ""


def lang_of(path: str) -> str:
    """Classify a file's language. Extension first; if the extension is
    missing or unknown, sniff the first line for a shebang (e.g.
    `#!/usr/bin/env perl`) or a vim/emacs modeline (e.g.
    `# -*- mode: perl -*-`). Falls back to "other" when nothing
    matches.

    Reason: without the sniff, extensionless build scripts (Perl's
    `Construct`, hand-rolled shell tools) got mis-parsed via the
    regex fallback, producing spurious unresolved-ref noise on every
    language-keyword in the file."""
    ext = os.path.splitext(path)[1].lower()
    hit = LANG_BY_EXT.get(ext)
    if hit is not None:
        return hit
    # Only sniff when the extension didn't resolve. Bounded to files
    # that actually exist (unit tests sometimes pass synthetic paths).
    if not os.path.isfile(path):
        return "other"
    first = _sniff_first_line(path).lstrip()
    # Shebang: `#!/usr/bin/env perl` or `#!/bin/bash -x`.
    if first.startswith("#!"):
        # Last path segment or first whitespace-separated token wins.
        rest = first[2:].strip()
        for tok in rest.split():
            base = os.path.basename(tok)
            if base in _SHEBANG_LANG:
                return _SHEBANG_LANG[base]
    # Emacs modeline: `-*- mode: perl -*-` / `-*- python -*-`.
    m_start = first.find("-*-")
    if m_start != -1:
        body = first[m_start + 3:]
        m_end = body.find("-*-")
        if m_end != -1:
            body = body[:m_end]
        body = body.lower().replace("mode:", "").strip()
        for tok in body.replace(";", " ").split():
            if tok in _MODELINE_LANG:
                return _MODELINE_LANG[tok]
    return "other"


def hash_file(path: str, chunk: int = 65536) -> str:
    h = hashlib.sha1()
    try:
        with open(path, "rb") as f:
            while True:
                b = f.read(chunk)
                if not b:
                    break
                h.update(b)
    except (OSError, PermissionError):
        return ""
    return h.hexdigest()


def rel(path: str, root: str) -> str:
    try:
        return str(Path(path).resolve().relative_to(Path(root).resolve()))
    except ValueError:
        return path


def read_text(path: str) -> str:
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read()
    except (OSError, PermissionError):
        return ""
